### ISSUE TITLE
Card terminal number field

### ISSUE THREAD

**Issue by sde1000** [sde1000/quicktill#103]
It would be useful at pubs with more than one card machine to have a field for the user to enter the card terminal number to store in the payment ref.

**Comment by sde1000** [comment]
No schema changes!

The reason the till software stores card receipt numbers in the 'ref' field of the payments table is so that we can search for the appropriate merchant receipt when there's a dispute.  This doesn't happen very often, fortunately, but it's useful to be able to do.

The card terminals we use for EMF all produce four-digit receipt numbers, and they all start from 0002!  I'd like the user interface to prompt for a terminal number too and then just put "{terminal number} {receipt number}" in the ref field instead - so if we have to look for a merchant receipt we know which pile to look in.

**Comment by zakx** [comment]
Ok, I understand. What would a terminal number look like?

**Comment by sde1000** [comment]
Literally just a number "1", "2", etc.

At EMF it'll be a single digit.  It's probably worth adding space for two digits because some sites might have **lots** of card terminals!

Also, it'd be good to have an option to turn this feature on and off, defaulting to off.  It'd be set in the config file where the CardPayment() payment method is instantiated.

**Comment by sde1000** [comment]
The code to lay out that popup is tedious already because of the optional 'cashback' field and its optional placement first or last.  Sorry!  One of the longer-term projects (no issue for it yet) is a better way to describe dialog layouts.  I'm very much reinventing the wheel here, just for the sake of keeping the ncurses display backend working.

**Comment by zakx** [comment]
The display stuff is indeed heavy on NIH, but also one of the reasons I really liked the software when I did some bar shifts on emf2016.

FWIW, I have started working on this and have already ported the cashback display to ui.moneyfield.

**Comment by sde1000** [comment]
Implemented by @zakx
