### ISSUE TITLE
JSON API for stock levels

### ISSUE THREAD

**Issue by drrk** [sde1000/quicktill#112]
Please provide an API for stock levels that can be queried remotely

**Comment by sde1000** [comment]
Ok, done (in a very basic way for EMFcamp).

http://bar.emfcamp.org/stock.json will return something like this:
```
{"stock": [{"remaining": "792.0", "description": "Milton Minotaur (3.3% ABV)", "unit": "pint"}, {"remaining": "1425.2", "description": "Milton Sparta (4.3% ABV)", "unit": "pint"}, {"remaining": "230.0", "description": "Club Mate Regular", "unit": "bottle"}, {"remaining": "14149.0", "description": "French Red Wine (14.0% ABV)", "unit": "ml"}]}
```

http://bar.emfcamp.org/locations.json will return something like this:
```
{"locations": ["Bar", "Fridge"]}
```

Using the locations from the previous request you can find out what's on sale at the moment using http://bar.emfcamp.org/location/[name].json (substitute the name) which will return something like this:
```
{"location": [{"price": "3.60", "description": "Milton Sparta (4.3% ABV)", "line": "01", "price_for_units": "1.0", "unit": "pint"}, {"price": "15.00", "description": "French Red Wine (14.0% ABV)", "line": "Red wine", "price_for_units": "750.0", "unit": "ml"}]}
```
