### ISSUE TITLE
Logo support on printed receipts

### ISSUE THREAD

**Issue by sde1000** [sde1000/quicktill#156]
The Cybar at EMF want to be able to print logos on receipts.

**Comment by jayaddison** [comment]
@sde1000 I attempted this yesterday evening and managed to get something working by using [`svglib`](https://github.com/deeplook/svglib) to read an SVG image and convert it to a `reportlab` format suitable for the existing [`printimage` method](https://github.com/sde1000/quicktill/blob/cc7e28ae502353bfa103488a7f26c045a02652f8/quicktill/pdrivers.py#L136-L137).

Testing that as PDF-to-window-from-till required a small adjustment to the `pdrivers.pdf_printer.process_canvas` code [around here](https://github.com/sde1000/quicktill/blob/cc7e28ae502353bfa103488a7f26c045a02652f8/quicktill/pdrivers.py#L980-L997).

Should the other printer drivers 'just work', or is PDF a special-case?  And in either case: should I follow-up with a pull request?  (I'll check with some EMF folks whether it's OK to use the EMF 2024 logo before that if so, to be on the safe side)

**Comment by sde1000** [comment]
They are all "special-case", unfortunately — although at the moment PDF and ESC/POS are the only two cases.

Are you converting to a PIL Image to send into reportlab? If so, that's a good step towards working with ESC/POS — there is suitable code in [python-escpos](https://github.com/python-escpos/python-escpos/tree/master) which I currently don't depend on but possibly ought to.

**Comment by jayaddison** [comment]
> They are all "special-case", unfortunately — although at the moment PDF and ESC/POS are the only two cases.

Ok.  Drats :)
 
> Are you converting to a PIL Image to send into reportlab? If so, that's a good step towards working with ESC/POS — there is suitable code in [python-escpos](https://github.com/python-escpos/python-escpos/tree/master) which I currently don't depend on but possibly ought to.

I'm not sure, to be honest - it's possible that `PIL` is involved somewhere; as far as I can tell though, `svglib` reads the input SVG as XML and then [renders a `reportlab`-format `Drawing` object](https://github.com/deeplook/svglib/blob/71cbd86d3e824192e36124a358db5514e6a2177c/svglib/svglib.py#L519) directly.

It's possible that my plan to read the native SVG logo as input is making this more complicated than it needs to be; even so, the code for the PDF implementation is fairly minimal (2 lines of `pdrivers.py` code, and then I've bodged in three lines to `printer.py` to load an SVG and `printimage` it)

**Comment by jayaddison** [comment]
> It's possible that my plan to read the native SVG logo as input is making this more complicated than it needs to be; even so, the code for the PDF implementation is fairly minimal (2 lines of `pdrivers.py` code, and then I've bodged in three lines to `printer.py` to load an SVG and `printimage` it)

Although that makes it sound easy: alignment/formatting is also required to make this look sensible, and I haven't implemented anything to do that yet (currently studying the text-based alignment code).

**Comment by sde1000** [comment]
Ah yes, *something* will have to rasterise the SVG to output it as esc/pos. Maybe easier to start with a PNG?

**Comment by jayaddison** [comment]
...or perhaps even BMP?

I've learned of the existence of [`escpos-tools`](https://github.com/receipt-print-hq/escpos-tools), some PHP code that can translate ESCPOS output into HTML, including images.

So now I'm thinking about trying to borrow and adapt some of the existing emulated QR raster code to handle black-and-white bitmap images.

**Comment by sde1000** [comment]
That could work!

It would probably be simpler than the existing raster QR printing code — that does its own interleaving to get a good quality print on a dot-matrix printer. Printing an image on a thermal printer doesn't need that.

**Comment by jayaddison** [comment]
While developing #282 I noticed in the [Epson ESC/P reference docs](https://download4.epson.biz/sec_pubs/pos/reference_en/escpos/fs_lparen_ce_fn62.html) (I _think_ Epson own the `epson.biz` domain in that URL; double-check if cautious) that there is an [`FS ( E` command](https://download4.epson.biz/sec_pubs/pos/reference_en/escpos/fs_lparen_ce_fn62.html) that, if I understand it correctly, can configure printing of a logo from the nonvolatile storage of some printer models.  I've opted to re-use the existing generic image rendering commands instead so far, but thought it'd be worth mentioning.
