### ISSUE TITLE
Colours

### ISSUE THREAD

**Issue by Marychesh** [sde1000/quicktill#180]
Would it be possible to make the button colours bolder and less alike when they are next to one another so they are easier to identify?

**Comment by Marychesh** [comment]
Thank you!

I think we just need the colours for spirits, wine, keg and ale, crisps and snacks to be extremely different to one another. So, for eg. Ales - blue, keg- purple, wine- a brighter pink, crisps and bar snacks- white?

**Comment by sde1000** [comment]
Ok, I'll try something along those lines but you might not like the precise colours I pick!

**Comment by Marychesh** [comment]
I am sure I will!

**Comment by sde1000** [comment]
Ok, I've changed those to the ones you suggested.  You can pick them up by restarting the till with Manage Till -> 8 -> 1.

**Comment by Marychesh** [comment]
Wicked thanks!

**Comment by Marychesh** [comment]
Also, the rose button doesn't work. Is there a way we can fix that ourselves?

**Comment by sde1000** [comment]
The Rosé button just needs the appropriate stock line adding to it.  Speedie and Joe know how to do this.

**Comment by sde1000** [comment]
...actually, no, the stock line is there.  It's just that no stock of J Laurens Rose Number 7 has been entered.

**Comment by sde1000** [comment]
It looks like it was entered as "Number 7 Sparkling Rose" instead.  You can fix the problem on the till by pressing Use Stock, then Rosé, then changing the type of stock to "Number 7 Sparkling Rose".

**Comment by Marychesh** [comment]
But all the wine is supposed to be on continuous

**Comment by sde1000** [comment]
It **is** a continuous stock line, it's just that it's been set up with one type of stock ("J Laurens Rose Number 7") and the stock has been entered as a different type ("Number 7 Sparkling Rose") so it can't find it.  Using the "Use Stock" function on a continuous stock line lets you change the type of stock it's looking for.

**Comment by Marychesh** [comment]
I have tried both of these on use stock, change stock type and neither work. 

The message that it says is ''This modifier can only be used with wine"

**Comment by sde1000** [comment]
Oh, right!  That message means it thinks the stock isn't wine, which usually means that the sale price hasn't been given as price per 750mls.  (The usual thing to do is forget about the 750ml bit and give the bottle price to 1ml instead.)

You can re-price the stock with Manage Stock -> 7 -> 6.  I've had a look: the "J Laurens" was priced per 1ml.  Since there isn't any stock of that type I've deleted it and set the stock line to point at the "Number 7 Sparkling Rose".  See if it works now?

**Comment by sde1000** [comment]
The Minuty is an odd one - the manufacturer is just "M"!  Currently there is no stock entered (presumably it was forgotten on Monday?), and there is no sale price set.  You'll need to enter it as a delivery from "Stock take".

**Comment by Marychesh** [comment]
Ok cool, thanks for all your help today

**Comment by Marychesh** [comment]
Me again, any way we can have a 'mark' button so we can highlight more than one item to delete

**Comment by sde1000** [comment]
Yes, it's over at the right next to the cursor keys!

**Comment by Marychesh** [comment]
forgive me!
