### ISSUE TITLE
Till freeze

### ISSUE THREAD

**Issue by Marychesh** [sde1000/quicktill#182]
The main till keeps freezing, for eg. up to 4 times in an evening. The buttons do not work and it means turning it off and on again to get it started again.

Thanks
Mary

**Comment by sde1000** [comment]
Next time it does this, can you check a few things out for me?

1. Is the clock at the top-right corner still running?
2. If the screen was off, does touching it wake it up or do you have to use the keyboard?
3. Is the till on the back bar still working?

I've had a look at the logs on the till and I can't see anything unusual in them, so I'm hoping that the answers to these questions will help me narrow it down a bit.

**Comment by Marychesh** [comment]
I will do, thanks Steve
