### ISSUE TITLE
Improve the default payment method

### ISSUE THREAD

**Issue by sde1000** [sde1000/quicktill#242]
At the moment the "default" payment method is simply the first payment method in the currently active list.

It is used in three places:

1. When the till user hits "Cash/Enter" in the context of an open transaction. (In some circumstances, for example if the transaction has been saved / recalled, the default payment type is not used.)
2. By the "Drink 'In'" function
3. When deferring a part-paid transaction that has non-deferrable payments

(Non-deferrable payments are those that are going to be included in the totals for a session whether the transaction is present or not, for example card payments.)

This isn't always helpful. These might need to be different payment methods, or disabled entirely.

To fix, add configuration options to set the payment method to use for all three cases; if the selected payment method is absent or not usable (disabled, doesn't support change, etc.) then disable the appropriate function.

**Comment by rohnsha0** [comment]
I party understood... and would love to at least give a try!

**Comment by sde1000** [comment]
Apologies: already done!
